export const ADD_PASSEMPLOYEE = 'ADD_PASSEMPLOYEE';
export const ADD_PASSEMPLOYEES = 'ADD_PASSEMPLOYEES';
export const DELETE_PASSEMPLOYEES = 'DELETE_PASSEMPLOYEES';
export const EDIT_PASSEMPLOYEES = 'EDIT_PASSEMPLOYEES';